name: http_interceptor
description: A lightweight, simple plugin that allows you to intercept request and response objects and modify them if desired.
version: 0.1.1
author: Alejandro Ulate (codingalecr) <codingalecr@gmail.com>
homepage: https://github.com/CodingAleCR/http_interceptor

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  http: ^0.13.1
